---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soon
  namespace: chewedfeed
  labels:
    name: soon
    app: soon
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  selector:
    matchLabels:
      name: soon
  template:
    metadata:
      labels:
        name: soon
        app: soon
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: soon
          image: containers.chewedfeed.com/k8sdeploy/soon:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: corpsite
  namespace: chewedfeed
  labels:
    name: corpsite
    app: corpsite
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: corpsite
